spring:
  datasource:
    druid:
      ds:
        #主数据库mysql
        default:
          url: jdbc:mysql://localhost:3306/learn?serverTimezone=GMT-8
          username: root
          password: root
          driverClassName: com.mysql.jdbc.Driver
      filter:
        stat:
          enabled: true
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
            merge-allow: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  basepackage: com.newerabc.zzgj_analyse.mapper.*
  xmlLocation: classpath:mapper/*.xml,classpath:mapper/*/*.xml
  mapper-locations: "classpath*:mapper/*.xml,classpath*:mapper/*/*.xml"
  typeAliasesPackage: com.newerabc.zzgj_analyse.mapper.*
  configuration:
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl